# Generated by Django 4.1.3 on 2022-12-07 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlecategory',
            name='css',
            field=models.CharField(default=1, max_length=128, verbose_name='CSS-класс'),
            preserve_default=False,
        ),
    ]
