# Generated by Django 4.1.4 on 2022-12-21 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='is_update',
            field=models.BooleanField(default=False),
        ),
    ]
