# Generated by Django 4.1.3 on 2022-12-07 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_articlecategory_css'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlecategory',
            name='css',
            field=models.CharField(default='bg-danger', max_length=128, verbose_name='CSS-класс'),
        ),
    ]
