# Generated by Django 4.1.3 on 2022-11-30 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_user_bio_remove_user_birthday'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='role',
            new_name='position',
        ),
    ]
