# Generated by Django 4.1.3 on 2022-12-01 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_rename_role_user_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='employee_token',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Имя почтового ящика (часть до @)'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_employee',
            field=models.BooleanField(default=False),
        ),
    ]
