# Generated by Django 4.1.3 on 2022-12-01 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_employee_token_user_is_employee'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='employee_token',
        ),
    ]
