# Generated by Django 4.1.3 on 2022-12-01 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_user_token_alter_user_avatar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='token',
        ),
        migrations.AddField(
            model_name='user',
            name='mailbox',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Токен сотрудника'),
        ),
        migrations.DeleteModel(
            name='HelperToken',
        ),
    ]
