# Generated by Django 4.1.4 on 2022-12-21 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_temporary_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_best',
            field=models.BooleanField(default=False),
        ),
    ]
