# Generated by Django 4.1.3 on 2022-12-01 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_remove_user_employee_token'),
    ]

    operations = [
        migrations.CreateModel(
            name='HelperToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mailbox_name', models.CharField(blank=True, max_length=128, null=True)),
            ],
            options={
                'verbose_name': 'Токен специалиста службы поддержи',
                'verbose_name_plural': 'Токены специалистов службы поддержки',
            },
        ),
    ]
