# Generated by Django 4.1.3 on 2022-11-30 17:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BaseRank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Ранг пользователя',
                'verbose_name_plural': 'Ранги пользователей',
            },
        ),
        migrations.CreateModel(
            name='DesiredRank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Необходимый ранг',
                'verbose_name_plural': 'Необходимые ранги',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256, verbose_name='Название')),
                ('price', models.IntegerField(verbose_name='Цена')),
                ('base_rank', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='store.baserank')),
                ('desired_rank', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='store.desiredrank')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
            },
        ),
    ]
