# Generated by Django 4.1.3 on 2022-12-03 16:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BaseRank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Ранг, с которого нужен буст',
                'verbose_name_plural': 'Ранги, с которых нужен буст',
            },
        ),
        migrations.CreateModel(
            name='DesiredRank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Ранг, до которого нужен буст',
                'verbose_name_plural': 'Ранги, до которых нужен буст',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256, verbose_name='Название')),
                ('price', models.IntegerField(verbose_name='Цена')),
                ('image', models.ImageField(null=True, upload_to='product_images', verbose_name='Изображение')),
                ('css', models.CharField(blank=True, max_length=128, verbose_name='CSS-класс')),
                ('base_rank', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='store.baserank')),
                ('desired_rank', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='store.desiredrank')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
            },
        ),
    ]
