# Generated by Django 4.1.3 on 2022-12-04 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='css',
        ),
        migrations.AddField(
            model_name='product',
            name='is_bestseller',
            field=models.BooleanField(blank=True, null=True, verbose_name='Бестселлер'),
        ),
    ]
