# Generated by Django 4.1.3 on 2022-12-01 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_alter_baserank_options_alter_desiredrank_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(null=True, upload_to='product_images', verbose_name='Изображение'),
        ),
    ]
