# Generated by Django 4.1.3 on 2022-12-05 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_remove_product_css_product_is_bestseller'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='price',
        ),
        migrations.AddField(
            model_name='product',
            name='current_price',
            field=models.IntegerField(default=100, verbose_name='Текущая цена'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='discount',
            field=models.BooleanField(blank=True, default=False, verbose_name='Товар со скидкой'),
        ),
        migrations.AddField(
            model_name='product',
            name='execution_time',
            field=models.CharField(blank=True, max_length=128, verbose_name='Время выполнения'),
        ),
        migrations.AddField(
            model_name='product',
            name='old_price',
            field=models.IntegerField(blank=True, default=100, verbose_name='Старая цена'),
            preserve_default=False,
        ),
    ]
