# Generated by Django 4.1.3 on 2022-12-02 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='css',
            field=models.CharField(blank=True, max_length=128, verbose_name='CSS-класс'),
        ),
    ]
