# Generated by Django 4.1.3 on 2022-12-01 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support_service', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='helper',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Имя почтового ящика (часть до @)'),
        ),
        migrations.AlterField(
            model_name='request',
            name='status',
            field=models.CharField(choices=[('W', 'Waiting'), ('P', 'In processing'), ('R', 'Resolved')], default='Waiting', max_length=300),
        ),
        migrations.DeleteModel(
            name='RequestStatus',
        ),
    ]
