# Generated by Django 4.1.3 on 2022-12-01 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support_service', '0002_request_helper_alter_request_status_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='request',
            options={'verbose_name': 'Запрос в службу поддержки', 'verbose_name_plural': 'Запросы в службу поддержки'},
        ),
        migrations.RemoveField(
            model_name='request',
            name='helper',
        ),
        migrations.AddField(
            model_name='request',
            name='mailbox',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Токен специалиста поддержки'),
        ),
    ]
